services:
  db:
    image: postgres:latest
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    command: >
      sh -c "
        docker-entrypoint.sh postgres &
        until pg_isready -U postgres; do sleep 1; done;
        psql -U postgres -d postgres -c 'CREATE EXTENSION IF NOT EXISTS \"pg_trgm\";'
        wait $$!
      "
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
