"""empty message

Revision ID: 1737d485f6be
Revises: 43f53b8c1941
Create Date: 2026-03-23 20:34:28.098692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1737d485f6be'
down_revision: Union[str, Sequence[str], None] = '43f53b8c1941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('image_path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'image_path')
    # ### end Alembic commands ###
