"""empty message

Revision ID: 43f53b8c1941
Revises: 
Create Date: 2026-03-18 19:01:47.642434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f53b8c1941'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.create_table('ingredient',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fats', sa.Float(), nullable=False),
    sa.Column('proteins', sa.Float(), nullable=False),
    sa.Column('carbohydrates', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ingredient_id'), 'ingredient', ['id'], unique=False)
    op.create_index('ix_ingredient_name_trgm', 'ingredient', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('recipe',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_id'), 'recipe', ['id'], unique=False)
    op.create_table('user',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('hash_password', sa.String(length=255), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('recipestep',
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('time_seconds', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipestep_id'), 'recipestep', ['id'], unique=False)
    op.create_index(op.f('ix_recipestep_recipe_id'), 'recipestep', ['recipe_id'], unique=False)
    op.create_table('recipestepingredient',
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('recipe_step_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_step_id'], ['recipestep.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipestepingredient_id'), 'recipestepingredient', ['id'], unique=False)
    op.create_index(op.f('ix_recipestepingredient_ingredient_id'), 'recipestepingredient', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_recipestepingredient_recipe_step_id'), 'recipestepingredient', ['recipe_step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP EXTENSION IF EXISTS pg_trgm CASCADE;")
    op.drop_index(op.f('ix_recipestepingredient_recipe_step_id'), table_name='recipestepingredient')
    op.drop_index(op.f('ix_recipestepingredient_ingredient_id'), table_name='recipestepingredient')
    op.drop_index(op.f('ix_recipestepingredient_id'), table_name='recipestepingredient')
    op.drop_table('recipestepingredient')
    op.drop_index(op.f('ix_recipestep_recipe_id'), table_name='recipestep')
    op.drop_index(op.f('ix_recipestep_id'), table_name='recipestep')
    op.drop_table('recipestep')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_recipe_id'), table_name='recipe')
    op.drop_table('recipe')
    op.drop_index('ix_ingredient_name_trgm', table_name='ingredient', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_ingredient_id'), table_name='ingredient')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
