"""empty message

Revision ID: 5b4cc20a4e36
Revises: 319474854954
Create Date: 2026-03-26 09:42:46.108149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b4cc20a4e36'
down_revision: Union[str, Sequence[str], None] = '319474854954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe', 'image_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe', 'image_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
