"""empty message

Revision ID: e5791584c363
Revises: 3128a897cd5f
Create Date: 2026-02-03 11:08:51.592618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5791584c363'
down_revision: Union[str, Sequence[str], None] = '3128a897cd5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('ingredient', 'descriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('descriptions', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('ingredient', 'description')
    # ### end Alembic commands ###
