"""empty message

Revision ID: 0e2a9fa01660
Revises: 456b3ebd185c
Create Date: 2026-04-30 18:12:27.160809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e2a9fa01660'
down_revision: Union[str, Sequence[str], None] = '456b3ebd185c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pursharedrecipes',
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('recipe_uuid', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_uuid'], ['recipe.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pursharedrecipes_id'), 'pursharedrecipes', ['id'], unique=False)
    op.create_index(op.f('ix_pursharedrecipes_recipe_uuid'), 'pursharedrecipes', ['recipe_uuid'], unique=False)
    op.create_index(op.f('ix_pursharedrecipes_user_uuid'), 'pursharedrecipes', ['user_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pursharedrecipes_user_uuid'), table_name='pursharedrecipes')
    op.drop_index(op.f('ix_pursharedrecipes_recipe_uuid'), table_name='pursharedrecipes')
    op.drop_index(op.f('ix_pursharedrecipes_id'), table_name='pursharedrecipes')
    op.drop_table('pursharedrecipes')
    # ### end Alembic commands ###
