"""empty message

Revision ID: 3642cbff8c12
Revises: ae0a040ed2c3
Create Date: 2026-04-23 20:14:34.211654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3642cbff8c12'
down_revision: Union[str, Sequence[str], None] = 'ae0a040ed2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tagrecipe', sa.Column('recipe_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_tagrecipe_recipe_uuid'), table_name='tagrecipe')
    op.create_index(op.f('ix_tagrecipe_recipe_id'), 'tagrecipe', ['recipe_id'], unique=False)
    op.drop_constraint(op.f('tagrecipe_recipe_uuid_fkey'), 'tagrecipe', type_='foreignkey')
    op.create_foreign_key(None, 'tagrecipe', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tagrecipe', 'recipe_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tagrecipe', sa.Column('recipe_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tagrecipe', type_='foreignkey')
    op.create_foreign_key(op.f('tagrecipe_recipe_uuid_fkey'), 'tagrecipe', 'recipe', ['recipe_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tagrecipe_recipe_id'), table_name='tagrecipe')
    op.create_index(op.f('ix_tagrecipe_recipe_uuid'), 'tagrecipe', ['recipe_uuid'], unique=False)
    op.drop_column('tagrecipe', 'recipe_id')
    # ### end Alembic commands ###
