"""empty message

Revision ID: 6fcc9059e2aa
Revises: 0e2a9fa01660
Create Date: 2026-04-30 18:22:08.760781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fcc9059e2aa'
down_revision: Union[str, Sequence[str], None] = '0e2a9fa01660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchasedrecipes',
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('recipe_uuid', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_uuid'], ['recipe.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchasedrecipes_id'), 'purchasedrecipes', ['id'], unique=False)
    op.create_index(op.f('ix_purchasedrecipes_recipe_uuid'), 'purchasedrecipes', ['recipe_uuid'], unique=False)
    op.create_index(op.f('ix_purchasedrecipes_user_uuid'), 'purchasedrecipes', ['user_uuid'], unique=False)
    op.drop_index(op.f('ix_pursharedrecipes_id'), table_name='pursharedrecipes')
    op.drop_index(op.f('ix_pursharedrecipes_recipe_uuid'), table_name='pursharedrecipes')
    op.drop_index(op.f('ix_pursharedrecipes_user_uuid'), table_name='pursharedrecipes')
    op.drop_table('pursharedrecipes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pursharedrecipes',
    sa.Column('user_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('recipe_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['recipe_uuid'], ['recipe.uuid'], name=op.f('pursharedrecipes_recipe_uuid_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], name=op.f('pursharedrecipes_user_uuid_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pursharedrecipes_pkey'))
    )
    op.create_index(op.f('ix_pursharedrecipes_user_uuid'), 'pursharedrecipes', ['user_uuid'], unique=False)
    op.create_index(op.f('ix_pursharedrecipes_recipe_uuid'), 'pursharedrecipes', ['recipe_uuid'], unique=False)
    op.create_index(op.f('ix_pursharedrecipes_id'), 'pursharedrecipes', ['id'], unique=False)
    op.drop_index(op.f('ix_purchasedrecipes_user_uuid'), table_name='purchasedrecipes')
    op.drop_index(op.f('ix_purchasedrecipes_recipe_uuid'), table_name='purchasedrecipes')
    op.drop_index(op.f('ix_purchasedrecipes_id'), table_name='purchasedrecipes')
    op.drop_table('purchasedrecipes')
    # ### end Alembic commands ###
