"""empty message

Revision ID: 732da55bf6bd
Revises: 63eed7966348
Create Date: 2026-03-29 20:24:49.095943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '732da55bf6bd'
down_revision: Union[str, Sequence[str], None] = '63eed7966348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backet',
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('recipe_uuid', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_uuid'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backet_id'), 'backet', ['id'], unique=False)
    op.create_index(op.f('ix_backet_recipe_uuid'), 'backet', ['recipe_uuid'], unique=False)
    op.create_index(op.f('ix_backet_user_uuid'), 'backet', ['user_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backet_user_uuid'), table_name='backet')
    op.drop_index(op.f('ix_backet_recipe_uuid'), table_name='backet')
    op.drop_index(op.f('ix_backet_id'), table_name='backet')
    op.drop_table('backet')
    # ### end Alembic commands ###
