"""empty message

Revision ID: 8a98b4a3864d
Revises: e830bc80d087
Create Date: 2026-04-13 12:33:13.836744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a98b4a3864d'
down_revision: Union[str, Sequence[str], None] = 'e830bc80d087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('basket_user_uuid_fkey'), 'basket', type_='foreignkey')
    op.drop_constraint(op.f('basket_recipe_uuid_fkey'), 'basket', type_='foreignkey')
    op.create_foreign_key(None, 'basket', 'recipe', ['recipe_uuid'], ['uuid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'basket', 'user', ['user_uuid'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'basket', type_='foreignkey')
    op.drop_constraint(None, 'basket', type_='foreignkey')
    op.create_foreign_key(op.f('basket_recipe_uuid_fkey'), 'basket', 'recipe', ['recipe_uuid'], ['uuid'])
    op.create_foreign_key(op.f('basket_user_uuid_fkey'), 'basket', 'user', ['user_uuid'], ['uuid'])
    # ### end Alembic commands ###
