"""empty message

Revision ID: ae0a040ed2c3
Revises: ba2acdf52f69
Create Date: 2026-04-21 18:33:41.232147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae0a040ed2c3'
down_revision: Union[str, Sequence[str], None] = 'ba2acdf52f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tagrecipe', sa.Column('tag_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_tagrecipe_tag'), table_name='tagrecipe')
    op.create_index(op.f('ix_tagrecipe_tag_id'), 'tagrecipe', ['tag_id'], unique=False)
    op.drop_constraint(op.f('tagrecipe_tag_fkey'), 'tagrecipe', type_='foreignkey')
    op.create_foreign_key(None, 'tagrecipe', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tagrecipe', 'tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tagrecipe', sa.Column('tag', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tagrecipe', type_='foreignkey')
    op.create_foreign_key(op.f('tagrecipe_tag_fkey'), 'tagrecipe', 'tag', ['tag'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tagrecipe_tag_id'), table_name='tagrecipe')
    op.create_index(op.f('ix_tagrecipe_tag'), 'tagrecipe', ['tag'], unique=False)
    op.drop_column('tagrecipe', 'tag_id')
    # ### end Alembic commands ###
