"""empty message

Revision ID: ba2acdf52f69
Revises: 
Create Date: 2026-04-21 17:59:17.833076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba2acdf52f69'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tag_id'), 'tag', ['id'], unique=False)
    op.create_index('ix_tag_name_trgm', 'tag', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('tagrecipe',
    sa.Column('tag', sa.Integer(), nullable=False),
    sa.Column('recipe_uuid', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_uuid'], ['recipe.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tagrecipe_id'), 'tagrecipe', ['id'], unique=False)
    op.create_index(op.f('ix_tagrecipe_recipe_uuid'), 'tagrecipe', ['recipe_uuid'], unique=False)
    op.create_index(op.f('ix_tagrecipe_tag'), 'tagrecipe', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tagrecipe_tag'), table_name='tagrecipe')
    op.drop_index(op.f('ix_tagrecipe_recipe_uuid'), table_name='tagrecipe')
    op.drop_index(op.f('ix_tagrecipe_id'), table_name='tagrecipe')
    op.drop_table('tagrecipe')
    op.drop_index('ix_tag_name_trgm', table_name='tag', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_tag_id'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
