"""empty message

Revision ID: e830bc80d087
Revises: f45ba2e9a648
Create Date: 2026-04-06 19:48:45.225621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e830bc80d087'
down_revision: Union[str, Sequence[str], None] = 'f45ba2e9a648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basket',
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('recipe_uuid', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_uuid'], ['recipe.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basket_id'), 'basket', ['id'], unique=False)
    op.create_index(op.f('ix_basket_recipe_uuid'), 'basket', ['recipe_uuid'], unique=False)
    op.create_index(op.f('ix_basket_user_uuid'), 'basket', ['user_uuid'], unique=False)
    op.drop_index(op.f('ix_backet_id'), table_name='backet')
    op.drop_index(op.f('ix_backet_recipe_uuid'), table_name='backet')
    op.drop_index(op.f('ix_backet_user_uuid'), table_name='backet')
    op.drop_table('backet')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backet',
    sa.Column('user_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('recipe_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['recipe_uuid'], ['recipe.uuid'], name=op.f('backet_recipe_uuid_fkey')),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], name=op.f('backet_user_uuid_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('backet_pkey'))
    )
    op.create_index(op.f('ix_backet_user_uuid'), 'backet', ['user_uuid'], unique=False)
    op.create_index(op.f('ix_backet_recipe_uuid'), 'backet', ['recipe_uuid'], unique=False)
    op.create_index(op.f('ix_backet_id'), 'backet', ['id'], unique=False)
    op.drop_index(op.f('ix_basket_user_uuid'), table_name='basket')
    op.drop_index(op.f('ix_basket_recipe_uuid'), table_name='basket')
    op.drop_index(op.f('ix_basket_id'), table_name='basket')
    op.drop_table('basket')
    # ### end Alembic commands ###
