"""empty message

Revision ID: ffd4fec025a1
Revises: 
Create Date: 2026-05-17 19:28:32.591884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffd4fec025a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fats', sa.Float(), nullable=False),
    sa.Column('proteins', sa.Float(), nullable=False),
    sa.Column('carbohydrates', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ingredient_id'), 'ingredient', ['id'], unique=False)
    op.create_index('ix_ingredient_name_trgm', 'ingredient', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('recipe',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('creator_uuid', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_id'), 'recipe', ['id'], unique=False)
    op.create_index('ix_recipe_name_trgm', 'recipe', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_recipe_uuid'), 'recipe', ['uuid'], unique=True)
    op.create_table('tag',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tag_id'), 'tag', ['id'], unique=False)
    op.create_index('ix_tag_name_trgm', 'tag', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('hash_password', sa.String(length=255), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('balance', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_uuid'), 'user', ['uuid'], unique=True)
    op.create_table('basket',
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('recipe_uuid', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_uuid'], ['recipe.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basket_id'), 'basket', ['id'], unique=False)
    op.create_index(op.f('ix_basket_recipe_uuid'), 'basket', ['recipe_uuid'], unique=False)
    op.create_index(op.f('ix_basket_user_uuid'), 'basket', ['user_uuid'], unique=False)
    op.create_table('purchasedrecipes',
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('recipe_uuid', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_uuid'], ['recipe.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchasedrecipes_id'), 'purchasedrecipes', ['id'], unique=False)
    op.create_index(op.f('ix_purchasedrecipes_recipe_uuid'), 'purchasedrecipes', ['recipe_uuid'], unique=False)
    op.create_index(op.f('ix_purchasedrecipes_user_uuid'), 'purchasedrecipes', ['user_uuid'], unique=False)
    op.create_table('recipestep',
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('time_seconds', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipestep_id'), 'recipestep', ['id'], unique=False)
    op.create_index(op.f('ix_recipestep_recipe_id'), 'recipestep', ['recipe_id'], unique=False)
    op.create_table('tagrecipe',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tagrecipe_id'), 'tagrecipe', ['id'], unique=False)
    op.create_index(op.f('ix_tagrecipe_recipe_id'), 'tagrecipe', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_tagrecipe_tag_id'), 'tagrecipe', ['tag_id'], unique=False)
    op.create_table('recipestepingredient',
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('recipe_step_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_step_id'], ['recipestep.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipestepingredient_id'), 'recipestepingredient', ['id'], unique=False)
    op.create_index(op.f('ix_recipestepingredient_ingredient_id'), 'recipestepingredient', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_recipestepingredient_recipe_step_id'), 'recipestepingredient', ['recipe_step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipestepingredient_recipe_step_id'), table_name='recipestepingredient')
    op.drop_index(op.f('ix_recipestepingredient_ingredient_id'), table_name='recipestepingredient')
    op.drop_index(op.f('ix_recipestepingredient_id'), table_name='recipestepingredient')
    op.drop_table('recipestepingredient')
    op.drop_index(op.f('ix_tagrecipe_tag_id'), table_name='tagrecipe')
    op.drop_index(op.f('ix_tagrecipe_recipe_id'), table_name='tagrecipe')
    op.drop_index(op.f('ix_tagrecipe_id'), table_name='tagrecipe')
    op.drop_table('tagrecipe')
    op.drop_index(op.f('ix_recipestep_recipe_id'), table_name='recipestep')
    op.drop_index(op.f('ix_recipestep_id'), table_name='recipestep')
    op.drop_table('recipestep')
    op.drop_index(op.f('ix_purchasedrecipes_user_uuid'), table_name='purchasedrecipes')
    op.drop_index(op.f('ix_purchasedrecipes_recipe_uuid'), table_name='purchasedrecipes')
    op.drop_index(op.f('ix_purchasedrecipes_id'), table_name='purchasedrecipes')
    op.drop_table('purchasedrecipes')
    op.drop_index(op.f('ix_basket_user_uuid'), table_name='basket')
    op.drop_index(op.f('ix_basket_recipe_uuid'), table_name='basket')
    op.drop_index(op.f('ix_basket_id'), table_name='basket')
    op.drop_table('basket')
    op.drop_index(op.f('ix_user_uuid'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index('ix_tag_name_trgm', table_name='tag', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_tag_id'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_recipe_uuid'), table_name='recipe')
    op.drop_index('ix_recipe_name_trgm', table_name='recipe', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_recipe_id'), table_name='recipe')
    op.drop_table('recipe')
    op.drop_index('ix_ingredient_name_trgm', table_name='ingredient', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_ingredient_id'), table_name='ingredient')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
